FROM jmeter-base:latest
MAINTAINER jens.pettersson

ARG JMETER_VERSION=5.3
		
EXPOSE 1099 50000
		
ENTRYPOINT $JMETER_HOME/bin/jmeter-server \
-Dserver.rmi.localport=50000 \
-Dserver_port=1099 \
-Jserver.rmi.ssl.disable=true
